[I 200707 11:49:16 inrepo:36] Testing notebook examples/notebooks/IntegrationOverPolytopes.ipynb
[I 200707 11:49:16 inrepo:45] Found kernel python3
[I 200707 11:49:18 execute:404] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/src/inrepo.py", line 112, in <module>
    main()
  File "/src/inrepo.py", line 108, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 74, in run_notebook
    exported = executenb(nb, cwd=os.path.dirname(nb_path), kernel_name=kernel_name)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
triangle = Polygon(Point(0,0), Point(1,1), Point(1,0))
plot_polytope(triangle)
print("Area of Triangle with vertices : (0,0), (1,1), (1,0) : ", polytope_integrate(triangle, 1))
print("x*y integrated over Triangle with vertices : (0,0), (1,1), (1,0) : ", polytope_integrate(triangle, x*y),"\n")

hexagon = Polygon(Point(0, 0), Point(-sqrt(3) / 2, 0.5),
                  Point(-sqrt(3) / 2, 3 / 2), Point(0, 2),
                  Point(sqrt(3) / 2, 3 / 2), Point(sqrt(3) / 2, 0.5))
plot_polytope(hexagon)
print("Area of regular hexagon with unit side length  : ", polytope_integrate(hexagon, 1))
print("x + y**2 integrated over regular hexagon with unit side length  : ", polytope_integrate(hexagon, x + y**2))

polys = [1, x, y, x*y]
print("1, x, y, x*y integrated over hexagon : ", polytope_integrate(hexagon, polys, max_degree=2))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-0bc9120627de>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mtriangle[0m [0;34m=[0m [0mPolygon[0m[0;34m([0m[0mPoint[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m0[0m[0;34m)[0m[0;34m,[0m [0mPoint[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m,[0m [0mPoint[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m0[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mplot_polytope[0m[0;34m([0m[0mtriangle[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mprint[0m[0;34m([0m[0;34m"Area of Triangle with vertices : (0,0), (1,1), (1,0) : "[0m[0;34m,[0m [0mpolytope_integrate[0m[0;34m([0m[0mtriangle[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mprint[0m[0;34m([0m[0;34m"x*y integrated over Triangle with vertices : (0,0), (1,1), (1,0) : "[0m[0;34m,[0m [0mpolytope_integrate[0m[0;34m([0m[0mtriangle[0m[0;34m,[0m [0mx[0m[0;34m*[0m[0my[0m[0;34m)[0m[0;34m,[0m[0;34m"\n"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.7/site-packages/sympy/integrals/intpoly.py[0m in [0;36mplot_polytope[0;34m(poly)[0m
[1;32m   1187[0m     [0myl[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mpoly[0m[0;34m.[0m[0mvertices[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m.[0m[0my[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1188[0m [0;34m[0m[0m
[0;32m-> 1189[0;31m     [0ml2ds[0m [0;34m=[0m [0mList2DSeries[0m[0;34m([0m[0mxl[0m[0;34m,[0m [0myl[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1190[0m     [0mp[0m [0;34m=[0m [0mPlot[0m[0;34m([0m[0ml2ds[0m[0;34m,[0m [0maxes[0m[0;34m=[0m[0;34m'label_axes=True'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1191[0m     [0mp[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.7/site-packages/sympy/plotting/plot.py[0m in [0;36m__init__[0;34m(self, list_x, list_y)[0m
[1;32m    581[0m         [0mnp[0m [0;34m=[0m [0mimport_module[0m[0;34m([0m[0;34m'numpy'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    582[0m         [0msuper[0m[0;34m([0m[0mList2DSeries[0m[0;34m,[0m [0mself[0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 583[0;31m         [0mself[0m[0;34m.[0m[0mlist_x[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mlist_x[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    584[0m         [0mself[0m[0;34m.[0m[0mlist_y[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mlist_y[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    585[0m         [0mself[0m[0;34m.[0m[0mlabel[0m [0;34m=[0m [0;34m'list'[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'array'
AttributeError: 'NoneType' object has no attribute 'array'


Container exited with status: {'Error': None, 'StatusCode': 1}
